# Configuration file for EasyCAT based ForceSensor Slave
vendor_id: 0x0000079a
product_id: 0xdeadbeef
tpdo:  # TxPDO
  - index: 0x1a00
    channels:
      - {index: 0x0006, sub_index: 1, type: int16, state_interface: force.0, factor: 1.0}
      - {index: 0x0006, sub_index: 2, type: int16, state_interface: force.1, factor: 1.0}
sm:  # Sync Manager
  - {index: 0, type: output, pdo: ~, watchdog: disable}
  - {index: 1, type: input, pdo: ~, watchdog: disable}
  - {index: 2, type: output, pdo: ~, watchdog: disable}
  - {index: 3, type: input, pdo: tpdo, watchdog: disable}
