<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="motor_drive">

  
  <material name="blue">
    <color rgba="0 0 0.8 1"/>
  </material>

  <material name="white">
    <color rgba="1 1 1 1"/>
  </material>

  <link name="world"/>
  
  <xacro:property name="width" value="0.4" />
  <xacro:property name="bodylen" value="0.672" />
  <xacro:property name="bodyheight" value="0.2" />

  <link name="base_link">
    <visual>
        <geometry>
            <box size="${bodylen} ${width} ${bodyheight}"/>
        </geometry>
        <origin xyz="0 0 0.11" rpy="0 0 0"/>
        <material name="blue"/>
    </visual>
    <collision>
        <geometry>
            <box size="${bodylen} ${width} ${bodyheight}"/>
        </geometry>
    </collision>
  </link>

  <joint name="base" type="fixed">
        <parent link="world"/>
        <child link="base_link"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <link name="wheel_right">
    <visual>
      <geometry>
          <cylinder radius="0.11" length="0.05"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <material name="white"/>
    </visual>
    <collision>
      <geometry>
          <cylinder radius="0.11" length="0.05"/>
      </geometry>
    </collision>
  </link>

  <joint name="joint_1" type="continuous">
        <parent link="base_link"/>
        <child link="wheel_right"/>
        <origin xyz="0 -${width/2} 0.11" rpy="${pi/2} 0 0"/>
        <axis xyz="0 0 1"/>
  </joint>

  <link name="wheel_left">
    <visual>
      <geometry>
          <cylinder radius="0.11" length="0.05"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <material name="white"/>
    </visual>
    <collision>
      <geometry>
          <cylinder radius="0.11" length="0.05"/>
      </geometry>
    </collision>
  </link>

  <joint name="joint_2" type="continuous">
        <parent link="base_link"/>
        <child link="wheel_left"/>
        <origin xyz="0 ${width/2} 0.11" rpy="-${pi/2} 0 0"/>
        <axis xyz="0 0 1"/>
  </joint>

  <xacro:include filename="$(find ethercat_diff_drive)/description/ros2_control/motor_diff_drive.ros2_control.xacro" />
  <xacro:motor_drive/>
</robot>
