# Configuration file for Beckhoff EL7221-9015 drive
vendor_id: 0x00000002
product_id: 0x1C353052
assign_activate: 0x0700  # DC Synch register
auto_fault_reset: true  # true = automatic fault reset, false = fault reset on rising edge command interface "reset_fault"
sdo:  # sdo data to be transferred at drive startup
  - {index: 0x2002, sub_index: 0x19, type: uint32, value: 24000} # Setup for 24V bus voltage
  - {index: 0x2002, sub_index: 0x14, type: uint32, value: 150}
  - {index: 0x2002, sub_index: 0x15, type: uint32, value: 244}
  - {index: 0x2002, sub_index: 0x13, type: uint16, value: 243}
  - {index: 0x2002, sub_index: 0x12, type: uint16, value: 5}
  - {index: 0x6080, sub_index: 0x00, type: uint32, value: 1400}
  - {index: 0x2003, sub_index: 0x15, type: int16, value: 270}
  - {index: 0x2003, sub_index: 0x2D, type: uint16, value: 752}
  - {index: 0x2003, sub_index: 0x18, type: uint32, value: 467}
  - {index: 0x2003, sub_index: 0x19, type: uint16, value: 21}
  - {index: 0x2003, sub_index: 0x16, type: uint32, value: 169}
  - {index: 0x2003, sub_index: 0x11, type: uint32, value: 44700}
  - {index: 0x2003, sub_index: 0x13, type: uint8, value: 4}
  - {index: 0x6075, sub_index: 0x00, type: uint32, value: 8000}
  - {index: 0x6060, sub_index: 0, type: uint8, value: 9}  # Mode of operation

rpdo:  # RxPDO = receive PDO Mapping
  - index: 0x1600
    channels:
      - {index: 0x6040, sub_index: 0, type: uint16, default: 0}  # Control word
  - index: 0x1601
    channels:
      #- {index: 0x60ff, sub_index: 0, type: int32, command_interface: velocity, factor: 2.503290804e6, default: 0}  # Target velocity
     #- {index: 0x60ff, sub_index: 0, type: int32, command_interface: velocity, factor: 976837, default: 0}  # Target velocity
      - {index: 0x60ff, sub_index: 0, type: int32, command_interface: velocity, factor: 1.953040327e6 , default: 0}  # Target velocity (60 (dişli motor tarafı) x 16 (motor gear head) x velocity encoder reso (268435) / (2 x pi x 21 ( disli teker tarafi)) )
  # - index: 0x1608
  #   channels:
      # - {index: 0x6060, sub_index: 0, type: int8, default: 9}  # Mode of operation

tpdo:  # TxPDO = transmit PDO Mapping
  - index: 0x1a00
    channels:
      - {index: 0x6041, sub_index: 0, type: uint16}  # Status word
  - index: 0x1a01
    channels:      
#      - {index: 0x6064, sub_index: 0, type: uint32, state_interface: position, factor: 970.972242686e-9}  # Position actual value
      - {index: 0x6064, sub_index: 0, type: uint32, state_interface: position, factor: 131.077459899e-9}  # Position actual value (2*PI*21/60x16/encoder_reso)
#       - {index: 0x6064, sub_index: 0, type: int32, state_interface: position, factor: 33.555829735e-6}  # Position actual value (2*PI*21/60x16/encoder_reso)
  - index: 0x1a02
    channels:      
       - {index: 0x606c, sub_index: 0, type: int32, state_interface: velocity, factor: 512.022197532e-9}  # Velocity actual value
sm:  # Sync Manager
  - {index: 0, type: output, pdo: ~, watchdog: disable}
  - {index: 1, type: input, pdo: ~, watchdog: disable}
  - {index: 2, type: output, pdo: rpdo, watchdog: disable}
  - {index: 3, type: input, pdo: tpdo, watchdog: disable}