controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["wheel_left_joint"]
    right_wheel_names: ["wheel_right_joint"]

    wheel_separation: 0.404
    wheel_radius: 0.0985
    wheel_separation_multiplier: 1.089
    left_wheel_radius_multiplier: 1.0 #0.0275
    right_wheel_radius_multiplier: 1.0 #-0.0275

    odom_frame_id: odom
    base_frame_id: base_footprint
    #pose_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    #twist_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

    position_feedback: true
    open_loop: false
    enable_odom_tf: true

    cmd_vel_timeout: 0.5 # seconds
    publish_limited_velocity: true
    velocity_rolling_window_size: 10

    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.has_jerk_limits: false
    linear.x.max_velocity: 2.0
    linear.x.min_velocity: -2.0
    linear.x.max_acceleration: 1.0
    linear.x.min_acceleration: -1.0
    linear.x.max_jerk: 0.0
    linear.x.min_jerk: 0.0

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: 2.0
    angular.z.min_velocity: -2.0
    angular.z.max_acceleration: 8.0
    angular.z.min_acceleration: -8.0
    angular.z.max_jerk: 0.0
    angular.z.min_jerk: 0.0

joint_state_broadcaster:
  ros__parameters:
    extra_joints:
      - CASTER_WHEEL_FRONT_LEFT_JOINT
      - CASTER_WHEEL_FRONT_RIGHT_JOINT
      - CASTER_WHEEL_BACK_LEFT_JOINT
      - CASTER_WHEEL_BACK_RIGHT_JOINT
      - SMALL_WHEEL_JOINT
      - SMALL_WHEEL_JOINT_0
      - SMALL_WHEEL_JOINT_1
      - SMALL_WHEEL_JOINT_2
