rtabmap:
  ros__parameters:
     #  ----  RGBD use -----
    #subscribe_depth: false
    #subscribe_rgb: false
    #subscribe_rgbd: true
    Rtabmap/DetectionRate: "1.0"
    subscribe_scan: false

    subscribe_scan_cloud: false
    #approx_sync: true
    gen_scan: true
    gen_scan_min_depth: 0.3

    frame_id: "base_link"
    odom_frame_id: "odom"

    RGBD/LinearUpdate: "0.1"
    RGBD/AngularUpdate: "0.1"
    RGBD/OptimizeFromGraphEnd: "false"
    Reg/Force3DoF: "true"
    Reg/Strategy: "0"  #0 Vis 1 ICP 2 VisICP
    Grid/FromDepth: "true"
    Grid/ScanDecimation: "0"
    Grid/Sensor: "1"
    Grid/RayTracing: "true"
    Grid/RangeMax: "4.0"
    Vis/minInLiers: "12"

