rtabmap:
  ros__parameters:
     #  ----  RGBD use -----
    #subscribe_depth: false
    #subscribe_rgb: false
    #subscribe_rgbd: true
    Rtabmap/DetectionRate: "2.0"
    subscribe_scan: false
    subscribe_scan_cloud: false
    subscribe_imu: true
    Mem/UseIMU: true
    approx_sync: false
    gen_scan: true
    gen_scan_min_depth: 0.3

    frame_id: "base_link"
    odom_frame_id: "odom"

    RGBD/LinearUpdate: "0.01"
    RGBD/AngularUpdate: "0.01"
    RGBD/OptimizeFromGraphEnd: "false"
    #RGBD/ProximityBySpace: "false"
    Reg/Force3DoF: "true"
    Reg/Strategy: "0"  #0 Vis 1 ICP 2 VisICP
    Grid/FromDepth: "true"
    Grid/ScanDecimation: "0"
    Grid/Sensor: "1"
    Grid/RayTracing: "true"
    Grid/RangeMax: "4.0"
    Vis/MinInliers: "12"
    Vis/EstimationType: "1"

